[package]
name = "onyx-cli"
description = "Command-line tools for the Onyx interchange format."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "onyx"
path = "src/main.rs"

[dependencies]
onyx-core.workspace = true
